services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: prompt-battle-db

    ports:
        - "3307:3306"

    env_file:
      - .env

    environment:
      MYSQL_DATABASE: prompt_battle
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin

    command: --bind-address=0.0.0.0
  
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: prompt-battle-phpmyadmin

    depends_on:
      - mysql

    ports:
      - "8080:80"

    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306